version: '2'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dwh
      - POSTGRES_PORT=5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      -   5435:5432/tcp

volumes:
  postgres_data: